version: '3.7'

services:
  nginx:
    image: nginx:1.29-alpine3.22
    container_name: reading-list-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/public:/var/www/html
    depends_on:
      - laravel
    networks:
      - external_network

  laravel:
    build:
      context: ./laravel
      dockerfile: ../docker/laravel/Dockerfile
    container_name: reading-list-laravel
    volumes:
      - ./laravel:/var/www/html
      - ./data/sqlite:/var/www/html/database/sqlite:rw
    expose:
      - "9000"
    networks:
      - external_network

networks:
  external_network:
    external: true
    name: ${NETWORK_NAME:-docker_external}
