services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: development
    container_name: reading-list-nginx
    volumes:
      - ./laravel/public:/var/www/html
    depends_on:
      - laravel
    networks:
      - internal
      - external

  laravel:
    build:
      context: ./laravel
      dockerfile: ../docker/laravel/Dockerfile
      target: development
    container_name: reading-list-laravel
    volumes:
      - ./laravel:/var/www/html
      - ./data/sqlite:/var/www/html/database/sqlite:rw
    expose:
      - "9000"
    networks:
      - internal

networks:
  internal:
    driver: bridge

  external:
    external: true
    name: ${NETWORK_NAME:-docker_external}
